// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: idl/cloudstorage/sm.proto

package sm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Biz           string                 `protobuf:"bytes,2,opt,name=biz,proto3" json:"biz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmRequest) Reset() {
	*x = SendSmRequest{}
	mi := &file_idl_cloudstorage_sm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmRequest) ProtoMessage() {}

func (x *SendSmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cloudstorage_sm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmRequest.ProtoReflect.Descriptor instead.
func (*SendSmRequest) Descriptor() ([]byte, []int) {
	return file_idl_cloudstorage_sm_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendSmRequest) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

type SendSmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmResponse) Reset() {
	*x = SendSmResponse{}
	mi := &file_idl_cloudstorage_sm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmResponse) ProtoMessage() {}

func (x *SendSmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cloudstorage_sm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmResponse.ProtoReflect.Descriptor instead.
func (*SendSmResponse) Descriptor() ([]byte, []int) {
	return file_idl_cloudstorage_sm_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendSmResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type VerifySmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biz           string                 `protobuf:"bytes,1,opt,name=biz,proto3" json:"biz,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySmRequest) Reset() {
	*x = VerifySmRequest{}
	mi := &file_idl_cloudstorage_sm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmRequest) ProtoMessage() {}

func (x *VerifySmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cloudstorage_sm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmRequest.ProtoReflect.Descriptor instead.
func (*VerifySmRequest) Descriptor() ([]byte, []int) {
	return file_idl_cloudstorage_sm_proto_rawDescGZIP(), []int{2}
}

func (x *VerifySmRequest) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *VerifySmRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifySmRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifySmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySmResponse) Reset() {
	*x = VerifySmResponse{}
	mi := &file_idl_cloudstorage_sm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmResponse) ProtoMessage() {}

func (x *VerifySmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_cloudstorage_sm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmResponse.ProtoReflect.Descriptor instead.
func (*VerifySmResponse) Descriptor() ([]byte, []int) {
	return file_idl_cloudstorage_sm_proto_rawDescGZIP(), []int{3}
}

func (x *VerifySmResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifySmResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_idl_cloudstorage_sm_proto protoreflect.FileDescriptor

var file_idl_cloudstorage_sm_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x64, 0x6c, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2f, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x73, 0x6d, 0x22,
	0x37, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x7a, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x7a, 0x22, 0x36, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x4d, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x62, 0x69, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x38, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x79, 0x0a, 0x0f, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x06,
	0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x12, 0x11, 0x2e, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x6d, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x53, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x12, 0x13, 0x2e, 0x73, 0x6d, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x73, 0x6d, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_idl_cloudstorage_sm_proto_rawDescOnce sync.Once
	file_idl_cloudstorage_sm_proto_rawDescData = file_idl_cloudstorage_sm_proto_rawDesc
)

func file_idl_cloudstorage_sm_proto_rawDescGZIP() []byte {
	file_idl_cloudstorage_sm_proto_rawDescOnce.Do(func() {
		file_idl_cloudstorage_sm_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_cloudstorage_sm_proto_rawDescData)
	})
	return file_idl_cloudstorage_sm_proto_rawDescData
}

var file_idl_cloudstorage_sm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_cloudstorage_sm_proto_goTypes = []any{
	(*SendSmRequest)(nil),    // 0: sm.SendSmRequest
	(*SendSmResponse)(nil),   // 1: sm.SendSmResponse
	(*VerifySmRequest)(nil),  // 2: sm.VerifySmRequest
	(*VerifySmResponse)(nil), // 3: sm.VerifySmResponse
}
var file_idl_cloudstorage_sm_proto_depIdxs = []int32{
	0, // 0: sm.ShortMsgService.SendSm:input_type -> sm.SendSmRequest
	2, // 1: sm.ShortMsgService.VerifySm:input_type -> sm.VerifySmRequest
	1, // 2: sm.ShortMsgService.SendSm:output_type -> sm.SendSmResponse
	3, // 3: sm.ShortMsgService.VerifySm:output_type -> sm.VerifySmResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_cloudstorage_sm_proto_init() }
func file_idl_cloudstorage_sm_proto_init() {
	if File_idl_cloudstorage_sm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_cloudstorage_sm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_cloudstorage_sm_proto_goTypes,
		DependencyIndexes: file_idl_cloudstorage_sm_proto_depIdxs,
		MessageInfos:      file_idl_cloudstorage_sm_proto_msgTypes,
	}.Build()
	File_idl_cloudstorage_sm_proto = out.File
	file_idl_cloudstorage_sm_proto_rawDesc = nil
	file_idl_cloudstorage_sm_proto_goTypes = nil
	file_idl_cloudstorage_sm_proto_depIdxs = nil
}
