// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: idl/cloudstorage/sm.proto

package sm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShortMsgService_SendSm_FullMethodName   = "/sm.ShortMsgService/SendSm"
	ShortMsgService_VerifySm_FullMethodName = "/sm.ShortMsgService/VerifySm"
)

// ShortMsgServiceClient is the client API for ShortMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortMsgServiceClient interface {
	SendSm(ctx context.Context, in *SendSmRequest, opts ...grpc.CallOption) (*SendSmResponse, error)
	VerifySm(ctx context.Context, in *VerifySmRequest, opts ...grpc.CallOption) (*VerifySmResponse, error)
}

type shortMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortMsgServiceClient(cc grpc.ClientConnInterface) ShortMsgServiceClient {
	return &shortMsgServiceClient{cc}
}

func (c *shortMsgServiceClient) SendSm(ctx context.Context, in *SendSmRequest, opts ...grpc.CallOption) (*SendSmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmResponse)
	err := c.cc.Invoke(ctx, ShortMsgService_SendSm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortMsgServiceClient) VerifySm(ctx context.Context, in *VerifySmRequest, opts ...grpc.CallOption) (*VerifySmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySmResponse)
	err := c.cc.Invoke(ctx, ShortMsgService_VerifySm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortMsgServiceServer is the server API for ShortMsgService service.
// All implementations must embed UnimplementedShortMsgServiceServer
// for forward compatibility.
type ShortMsgServiceServer interface {
	SendSm(context.Context, *SendSmRequest) (*SendSmResponse, error)
	VerifySm(context.Context, *VerifySmRequest) (*VerifySmResponse, error)
	mustEmbedUnimplementedShortMsgServiceServer()
}

// UnimplementedShortMsgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortMsgServiceServer struct{}

func (UnimplementedShortMsgServiceServer) SendSm(context.Context, *SendSmRequest) (*SendSmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSm not implemented")
}
func (UnimplementedShortMsgServiceServer) VerifySm(context.Context, *VerifySmRequest) (*VerifySmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySm not implemented")
}
func (UnimplementedShortMsgServiceServer) mustEmbedUnimplementedShortMsgServiceServer() {}
func (UnimplementedShortMsgServiceServer) testEmbeddedByValue()                         {}

// UnsafeShortMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortMsgServiceServer will
// result in compilation errors.
type UnsafeShortMsgServiceServer interface {
	mustEmbedUnimplementedShortMsgServiceServer()
}

func RegisterShortMsgServiceServer(s grpc.ServiceRegistrar, srv ShortMsgServiceServer) {
	// If the following call pancis, it indicates UnimplementedShortMsgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShortMsgService_ServiceDesc, srv)
}

func _ShortMsgService_SendSm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortMsgServiceServer).SendSm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortMsgService_SendSm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortMsgServiceServer).SendSm(ctx, req.(*SendSmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortMsgService_VerifySm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortMsgServiceServer).VerifySm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortMsgService_VerifySm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortMsgServiceServer).VerifySm(ctx, req.(*VerifySmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortMsgService_ServiceDesc is the grpc.ServiceDesc for ShortMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sm.ShortMsgService",
	HandlerType: (*ShortMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSm",
			Handler:    _ShortMsgService_SendSm_Handler,
		},
		{
			MethodName: "VerifySm",
			Handler:    _ShortMsgService_VerifySm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/cloudstorage/sm.proto",
}
